// workers/shared/studio-tools/src/components/react/ToolCard.tsx
/** @jsxImportSource react */
/**
 * ToolCard - Clickable card representing a single tool (React version)
 */

import type { ToolDefinition } from '../../types';

export interface ToolCardProps {
  tool: ToolDefinition;
  selected?: boolean;
  disabled?: boolean;
  disabledReason?: string;
  onClick: () => void;
}

export function ToolCard({ tool, selected, disabled, disabledReason, onClick }: ToolCardProps) {
  const handleClick = () => {
    if (!disabled) {
      onClick();
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      handleClick();
    }
  };

  const className = [
    'st-tool-card',
    selected && 'st-tool-card--selected',
    disabled && 'st-tool-card--disabled',
  ].filter(Boolean).join(' ');

  return (
    <div
      className={className}
      style={{ '--tool-color': tool.color ?? 'var(--accent-color)' } as React.CSSProperties}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      role="button"
      tabIndex={disabled ? -1 : 0}
      aria-pressed={selected}
      aria-disabled={disabled}
      title={disabled ? disabledReason : tool.description}
    >
      <div className="st-tool-card__icon">
        {tool.icon}
      </div>

      <div className="st-tool-card__content">
        <h4 className="st-tool-card__name">{tool.name}</h4>
        <p className="st-tool-card__description">{tool.description}</p>
      </div>

      {disabled && disabledReason && (
        <div className="st-tool-card__lock">
          <span className="st-tool-card__lock-icon">🔒</span>
        </div>
      )}

      {tool.tier !== 'free' && (
        <div className={`st-tool-card__tier st-tool-card__tier--${tool.tier}`}>
          {tool.tier.toUpperCase()}
        </div>
      )}
    </div>
  );
}

// workers/shared/studio-tools/src/components/solid/ToolCard.tsx
/**
 * ToolCard - Clickable card representing a single tool
 */

import { Component, Show } from 'solid-js';
import type { ToolDefinition } from '../../types';

export interface ToolCardProps {
  tool: ToolDefinition;
  selected?: boolean;
  disabled?: boolean;
  disabledReason?: string;
  onClick: () => void;
}

export const ToolCard: Component<ToolCardProps> = (props) => {
  const handleClick = () => {
    if (!props.disabled) {
      props.onClick();
    }
  };

  const handleKeyDown = (e: KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      handleClick();
    }
  };

  return (
    <div
      class="st-tool-card"
      classList={{
        'st-tool-card--selected': props.selected,
        'st-tool-card--disabled': props.disabled,
      }}
      style={{ '--tool-color': props.tool.color ?? 'var(--accent-color)' }}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
      role="button"
      tabIndex={props.disabled ? -1 : 0}
      aria-pressed={props.selected}
      aria-disabled={props.disabled}
      title={props.disabled ? props.disabledReason : props.tool.description}
    >
      <div class="st-tool-card__icon">
        {props.tool.icon}
      </div>

      <div class="st-tool-card__content">
        <h4 class="st-tool-card__name">{props.tool.name}</h4>
        <p class="st-tool-card__description">{props.tool.description}</p>
      </div>

      <Show when={props.disabled && props.disabledReason}>
        <div class="st-tool-card__lock">
          <span class="st-tool-card__lock-icon">🔒</span>
        </div>
      </Show>

      <Show when={props.tool.tier !== 'free'}>
        <div class="st-tool-card__tier" classList={{
          'st-tool-card__tier--pro': props.tool.tier === 'pro',
          'st-tool-card__tier--premium': props.tool.tier === 'premium',
        }}>
          {props.tool.tier.toUpperCase()}
        </div>
      </Show>
    </div>
  );
};
