// workers/shared/studio-tools/src/components/react/ToolDrawer.tsx
/** @jsxImportSource react */
/**
 * ToolDrawer - Slide-out panel for configuring and executing a tool (React version)
 */

import { useState, useEffect } from 'react';
import type { ToolDefinition, ToolResult } from '../../types';
import { ParameterInput } from './ParameterInput';
import { ResultPreview, type ViewMode } from './ResultPreview';

export interface ToolDrawerProps {
  tool: ToolDefinition;
  content: string;
  open: boolean;
  onClose: () => void;

  // Parameter state
  parameters: Record<string, unknown>;
  onParameterChange: (name: string, value: unknown) => void;

  // Execution
  onExecute: () => void;
  isExecuting: boolean;

  // Result
  result: ToolResult | null;

  // Actions
  onApply: () => void;
  onCopy?: () => void;
  onChain?: (nextToolId: string) => void;
  onDiscard: () => void;
}

export function ToolDrawer({
  tool,
  content,
  open,
  onClose,
  parameters,
  onParameterChange,
  onExecute,
  isExecuting,
  result,
  onApply,
  onCopy,
  onChain,
  onDiscard,
}: ToolDrawerProps) {
  const [viewMode, setViewMode] = useState<ViewMode>('result-only');
  const [validationErrors, setValidationErrors] = useState<Record<string, string>>({});

  // Reset view mode when tool changes
  useEffect(() => {
    setViewMode('result-only');
    setValidationErrors({});
  }, [tool.id]);

  const validateAndExecute = () => {
    const errors: Record<string, string> = {};

    // Check required parameters
    for (const param of tool.parameters) {
      if (param.required) {
        const value = parameters[param.name];
        if (value === undefined || value === null || value === '') {
          errors[param.name] = `${param.label} is required`;
        }
      }
    }

    // Validate input text
    if (tool.inputType === 'text' && tool.validateInput) {
      const validation = tool.validateInput(content);
      if (!validation.valid) {
        errors['_input'] = validation.error ?? 'Invalid input';
      }
    }

    setValidationErrors(errors);

    if (Object.keys(errors).length === 0) {
      onExecute();
    }
  };

  const canExecute = () => {
    if (isExecuting) return false;
    if (tool.inputType === 'text' && !content.trim()) return false;
    return true;
  };

  return (
    <div className={`st-drawer ${open ? 'st-drawer--open' : ''}`}>
      <div className="st-drawer__backdrop" onClick={onClose} />

      <div className="st-drawer__panel">
        {/* Header */}
        <div className="st-drawer__header">
          <div className="st-drawer__header-content">
            <span className="st-drawer__icon">{tool.icon}</span>
            <div className="st-drawer__title-group">
              <h3 className="st-drawer__title">{tool.name}</h3>
              <p className="st-drawer__description">{tool.description}</p>
            </div>
          </div>
          <button className="st-drawer__close" onClick={onClose} aria-label="Close">
            ×
          </button>
        </div>

        {/* Input validation error */}
        {validationErrors['_input'] && (
          <div className="st-drawer__input-error">
            {validationErrors['_input']}
          </div>
        )}

        {/* Content preview (when input is text) */}
        {tool.inputType === 'text' && content && (
          <div className="st-drawer__input-preview">
            <div className="st-drawer__input-preview-label">Input text:</div>
            <div className="st-drawer__input-preview-text">
              {content.length > 200
                ? content.substring(0, 200) + '...'
                : content}
            </div>
            <div className="st-drawer__input-preview-length">
              {content.length} characters
            </div>
          </div>
        )}

        {/* Parameters */}
        {tool.parameters.length > 0 && (
          <div className="st-drawer__parameters">
            {tool.parameters.map((param) => (
              <ParameterInput
                key={param.name}
                parameter={param}
                value={parameters[param.name] ?? param.default}
                onChange={(value) => onParameterChange(param.name, value)}
                disabled={isExecuting}
                error={validationErrors[param.name]}
              />
            ))}
          </div>
        )}

        {/* Execute button */}
        {!result && (
          <div className="st-drawer__execute">
            <button
              className="st-drawer__execute-button"
              onClick={validateAndExecute}
              disabled={!canExecute()}
            >
              {isExecuting ? (
                <>
                  <span className="st-drawer__spinner" />
                  Processing...
                </>
              ) : (
                <>Run {tool.name}</>
              )}
            </button>
          </div>
        )}

        {/* Result preview */}
        {result && (
          <div className="st-drawer__result">
            <ResultPreview
              result={result}
              originalContent={content}
              viewMode={viewMode}
              onViewModeChange={setViewMode}
              onApply={onApply}
              onCopy={onCopy}
              onChain={onChain}
              onDiscard={onDiscard}
            />
          </div>
        )}

        {/* Long description / help */}
        {tool.longDescription && (
          <details className="st-drawer__help">
            <summary>How it works</summary>
            <p>{tool.longDescription}</p>
          </details>
        )}
      </div>
    </div>
  );
}

// workers/shared/studio-tools/src/components/solid/ToolDrawer.tsx
/**
 * ToolDrawer - Slide-out panel for configuring and executing a tool
 */

import { Component, Show, For, createSignal, createEffect } from 'solid-js';
import type { ToolDefinition, ToolResult } from '../../types';
import { ParameterInput } from './ParameterInput';
import { ResultPreview, ViewMode } from './ResultPreview';

export interface ToolDrawerProps {
  tool: ToolDefinition;
  content: string;
  open: boolean;
  onClose: () => void;

  // Parameter state
  parameters: Record<string, unknown>;
  onParameterChange: (name: string, value: unknown) => void;

  // Execution
  onExecute: () => void;
  isExecuting: boolean;

  // Result
  result: ToolResult | null;

  // Actions
  onApply: () => void;
  onCopy?: () => void;
  onChain?: (nextToolId: string) => void;
  onDiscard: () => void;
}

export const ToolDrawer: Component<ToolDrawerProps> = (props) => {
  const [viewMode, setViewMode] = createSignal<ViewMode>('result-only');
  const [validationErrors, setValidationErrors] = createSignal<Record<string, string>>({});

  // Reset view mode when tool changes
  createEffect(() => {
    props.tool.id;
    setViewMode('result-only');
    setValidationErrors({});
  });

  const validateAndExecute = () => {
    const errors: Record<string, string> = {};

    // Check required parameters
    for (const param of props.tool.parameters) {
      if (param.required) {
        const value = props.parameters[param.name];
        if (value === undefined || value === null || value === '') {
          errors[param.name] = `${param.label} is required`;
        }
      }
    }

    // Validate input text
    if (props.tool.inputType === 'text' && props.tool.validateInput) {
      const validation = props.tool.validateInput(props.content);
      if (!validation.valid) {
        errors['_input'] = validation.error ?? 'Invalid input';
      }
    }

    setValidationErrors(errors);

    if (Object.keys(errors).length === 0) {
      props.onExecute();
    }
  };

  const canExecute = () => {
    if (props.isExecuting) return false;
    if (props.tool.inputType === 'text' && !props.content.trim()) return false;
    return true;
  };

  return (
    <div class="st-drawer" classList={{ 'st-drawer--open': props.open }}>
      <div class="st-drawer__backdrop" onClick={props.onClose} />

      <div class="st-drawer__panel">
        {/* Header */}
        <div class="st-drawer__header">
          <div class="st-drawer__header-content">
            <span class="st-drawer__icon">{props.tool.icon}</span>
            <div class="st-drawer__title-group">
              <h3 class="st-drawer__title">{props.tool.name}</h3>
              <p class="st-drawer__description">{props.tool.description}</p>
            </div>
          </div>
          <button class="st-drawer__close" onClick={props.onClose} aria-label="Close">
            ×
          </button>
        </div>

        {/* Input validation error */}
        <Show when={validationErrors()['_input']}>
          <div class="st-drawer__input-error">
            {validationErrors()['_input']}
          </div>
        </Show>

        {/* Content preview (when input is text) */}
        <Show when={props.tool.inputType === 'text' && props.content}>
          <div class="st-drawer__input-preview">
            <div class="st-drawer__input-preview-label">Input text:</div>
            <div class="st-drawer__input-preview-text">
              {props.content.length > 200
                ? props.content.substring(0, 200) + '...'
                : props.content}
            </div>
            <div class="st-drawer__input-preview-length">
              {props.content.length} characters
            </div>
          </div>
        </Show>

        {/* Parameters */}
        <Show when={props.tool.parameters.length > 0}>
          <div class="st-drawer__parameters">
            <For each={props.tool.parameters}>
              {(param) => (
                <ParameterInput
                  parameter={param}
                  value={props.parameters[param.name] ?? param.default}
                  onChange={(value) => props.onParameterChange(param.name, value)}
                  disabled={props.isExecuting}
                  error={validationErrors()[param.name]}
                />
              )}
            </For>
          </div>
        </Show>

        {/* Execute button */}
        <Show when={!props.result}>
          <div class="st-drawer__execute">
            <button
              class="st-drawer__execute-button"
              onClick={validateAndExecute}
              disabled={!canExecute()}
            >
              <Show when={props.isExecuting} fallback={<>Run {props.tool.name}</>}>
                <span class="st-drawer__spinner" />
                Processing...
              </Show>
            </button>
          </div>
        </Show>

        {/* Result preview */}
        <Show when={props.result}>
          <div class="st-drawer__result">
            <ResultPreview
              result={props.result!}
              originalContent={props.content}
              viewMode={viewMode()}
              onViewModeChange={setViewMode}
              onApply={props.onApply}
              onCopy={props.onCopy}
              onChain={props.onChain}
              onDiscard={props.onDiscard}
            />
          </div>
        </Show>

        {/* Long description / help */}
        <Show when={props.tool.longDescription}>
          <details class="st-drawer__help">
            <summary>How it works</summary>
            <p>{props.tool.longDescription}</p>
          </details>
        </Show>
      </div>
    </div>
  );
};
